import Header from './Header'
import './globals.css'


export const metadata = {
  title: 'Lingua-app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body suppressHydrationWarning={true} className='font-axiforma'>
        <Header />
        {children}
      </body>
    </html>
  )
}
